src/lib/fascist.c
https://github.com/cracklib/cracklib/blob/master/src/lib/fascist.c#L613
https://github.com/cracklib/cracklib/blob/master/src/lib/fascist.c#L625
minor change to use same sentence
=> Normalize string to avoid two translatable strings

src/util/cracklib-format
Signed-off-by: Stefan Sørensen <stefan.sorensen@spectralink.com>
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
[Retrieved from:
https://git.buildroot.net/buildroot/tree/package/cracklib/0003-Force-grep-to-treat-the-input-as-text-when-formattin.patch]
=> Force grep to treat the input as text when formatting word files

src/util/Makefile.am
Fixes:
- http://autobuild.buildroot.org/results/a16b8ce12f01ad37a2174422e39465b80108ff19
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> util/Makefile.am: fix link with lintl

src/util/cracklib-format
With the distributed word files when "create-cracklib-dict" is run
it gives several output messages:
skipping line: 1
warning: input out of order
The "skipping line" message is due to the presence of a blank line
(after other line processing in cracklib-format).
The "input out of order" warnings are due to extremely long lines
present in the supplied myspace.txt.bz2 file - line 31,566 is 6341
characters long! cracklib-packer splits lines longer than 1022
characters long and treats them as distinct lines which then may
appear to be out of sort order due to the splitting.
Whilst the provided myspace.txt.bz2 file should be modified to remove
or truncate the very long line the same problem could appear for users
with other sourced word files.
This change truncates any lines from word files at …
=> Fixes create-cracklib-dict warnings

src/util/packer.c
Fix an issue that dict words in the file pw_dict are deleted when create-cracklib-dict or cracklib-packer has no valid input data.
For example:
Give an empty file or a file that does't exist or a file has no valid input words to create-cracklib-dict, all words in pw_dict are deleted. 
$ cracklib-create-dict test
Run cracklib-packer and press Enter, all words in pw_dict are deleted. 
$ cracklib-packer
=> Fix an issue that all words are deleted when there is no valid input data

src/util/Makefile.am, src/util/check.c
This fixes localised message output in the following cases:
* non-standard PREFIX on GNU systems
GNU systems wouldn't be able to find the message catalog files.
* musl systems
musl relies on bindtextdomain being called; it has no default catalog path.
=> util: Call bindtextdomain to initialise gettext

src/util/testnum.c, src/util/teststr.c
Error log:
...
$ ./testnum
(null).pwd.gz: No such file or directory
PWOpen: No such file or directory
$ ./util/teststr
(null).pwd.gz: No such file or directory
PWOpen: No such file or directory
...
Set DEFAULT_CRACKLIB_DICT as the path of  PWOpen
Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
=> cracklib: fix testnum and teststr failures

src/python/Makefile.am, src/python/_cracklib.c
split out from https://github.com/cracklib/cracklib/pull/50 , same thing but for python.
=> python: ensure to call bindtextdomain before textdomain

src/python/setup.py.in
We need this for config.h added by 2e0f854bada720ff4fbd13aed4f87087d466274d.
=> python: adjust include path for builddir

src/lib/rules.c
The area array in the PolyPurge function was not marked static like in the other functions.
=> Make buffer static and avoid returning stack-allocated memory

src/lib/fascist.c, src/lib/packlib.c, src/lib/rules.c, src/lib/stringlib.c, src/util/check.c, src/util/packer.c, src/util/unpacker.c
This trivial change converts function definitions to use ANSI C. Checked with `CFLAGS='-std=c99 -Werror=old-style-definition' ./configure && make` on Ubuntu 22.04.2 with GCC 11.4.0.
=> convert K&R function declarations to ANSI C

src/python/test_cracklib.py
The test suite still used the obsolete assertEquals() function which was a deprecated alias for assertEqual() (without the s) and got dropped from Python 3.12.
Use the replacement instead so the test-suite can run with Python 3.12.
=> Fix test-suite so it can run with Python 3.12

src/doc/cracklib-check.8, src/util/check.c
Add option --no-echo to cracklib-check, shutdown echoing when read password from the terminal. 
If --no-echo is not specified, echoing plaintext to the terminal is default as the same as before. 
Fix: #77
Before:
[root@localhost ~]# cracklib-check 
29fjosajf
29fjosajf: OK
jf8
jf8: it is WAY too short
^C
[root@localhost ~]#
[root@localhost ~]# cracklib-check < test 
alfdj22: OK
faj2: it is too short
2: it is WAY too short
af2: it is WAY too short
Tls02: it is too short
lfjj02rqka: OK
ajf0nfn: OK
[root@localhost ~]# 
After:
[root@localhost ~]# cracklib-check 
alfdj22
alfdj22: OK
dh2
dh2: it is WAY too short
^C
[root@localhost ~]# 
[root@localhost ~]# cracklib-check --no-echo
TestPwd12: it is based on a dictionary word
It is OK
[root@localhost ~]#  
[root@localhost ~]# cracklib-check …
=> cracklib-check: improve output when checking passwords

src/lib/fascist.c, src/lib/packer.h, src/lib/packlib.c, src/lib/rules.c, src/util/cracklib-format
Based on fedora patch:
commit a483b3bf78a0430b819ee17033e97e481eb57731
Author: Tomas Mraz <tmraz@fedoraproject.org>
Date:   Wed Aug 21 15:36:05 2013 +0200
fix the python module to work with compressed dictionaries (#972542)
- fix various dictionary lookup errors (#986400, #986401)
- make the library reentrant and fix compilation warnings
=> upstream fedora patches for cracklib

src/lib/packlib.c
This does two things:
1. fixes whitespace in the packlib.c file (only) to be consistent rather than a mix of indentation levels and tabs/spaces
2. removes support for reading "broken" 64-bit dictionaries as per issue #79
=> Remove support for reading 64-bit dictionaries

src/lib/fascist.c
The maxrepeat variable in FascistLookUser is not used and so it was removed.  This helps address issue #8.
=> Remove unused variable in fascist.c

src/util/Makefile.am, src/util/testlib.c, src/util/testnum.c, src/util/teststr.c
This adds an automatic test to make sure that `cracklib` is working.  It creates a simple dictionary from the `cracklib-small` word list and then tests each of those words against the dictionary.  The expected result, of course, is that none of the words are judged to be "ok" by `cracklib` and that's what this test checks.  This addresses issue #83.  A separate PR will address the out-of-source (OOS) issues noted there.
As an example, running `make check` produces a `test-suite.log` file which contains this:
```
==========================================
cracklib 2.9.12: util/test-suite.log
==========================================
```
=> Enhance testing

src/configure.ac, src/util/Makefile.am
If cracklib is being cross-compiled, the resulting binaries probably don't run on the build machine.  For that reason, this changes the "make check" test to not attempt to run the test if the code is being cross-compiled.  This relates to #83.
=> Omit existing check test if cross-compiling

src/configure.ac, src/lib/packer.h, src/lib/packlib.c, src/lib/rules.c, src/util/Makefile.am
This addresses #74 by:
1. always writing dictionary files as little-endian, although it can read either little-endian or big-endian files.
2. adding a test to verify that it can read from either endian
3. making two changes to yield performance gains to more than offset any performance loss from this change
4. fixing an earlier "make check" to have the correct directories
=> Always save as little endian

src/Makefile.am, src/autogen.sh, src/configure.ac
This follows up on the suggestion in #76 which points out that autoreconf automatically calls autopoint when it detects that gettext is in use.  Also, there is no need anything special for the m4 files since autoconf (and autoreconf) will already automatically take care of those, too.
=> Simplify autogen.sh

src/doc/Makefile.am, src/doc/create-cracklib-dict.8
This one man page was not added in https://github.com/cracklib/cracklib/pull/37. It is extracted from Debian archive
https://archive.debian.org/debian/pool/main/c/cracklib2/cracklib2_2.9.2-5.debian.tar.xz
=> Add man page for create-cracklib-dict

src/util/cracklib-format
The commit https://github.com/cracklib/cracklib/commit/54568719798c2ecc5f72d6ab608ad0681fc4ce7c removed including of special characters when preprocessing the wordlist via `cracklib-format`.
Before changes introduced in this PR, the `cracklib-format` called from `create-cracklib-dict` removed special characters from the wordlist and therefore `cracklib-check` with such dictionary was not able to correctly recognize inputs based on dictionary words.
To reproduce:
```
$ create-cracklib-dict /usr/share/dict/words
$ grep -E '\w*[^\w\s]\w*' /usr/share/dict/words | cracklib-check | grep ': OK'
2,4,5-t: OK
Aaron's-beard: OK
Adam's-needle: OK
adder's-grass: OK
...
```
Previously, this change was also applied to Fedora (f37) https://src.fedoraproject.org/rpms/cracklib/blob/f37/f/cracklib-2.9.6-simp …
=> Preserve special characters in cracklib-format

src/lib/packlib.c
After https://github.com/cracklib/cracklib/commit/14d22080bc8dbebf18685c57572a3c8adc16e390, cracklib fails to build on Darwin due to use of size-specific functions from `endian.h` that aren’t available on Darwin. This PR restores support for Darwin by defining them in terms of their equivalents from `OSByteOrder.h`.
=> Use OSByteOrder functions on Darwin

src/configure.ac
Translation file available, but not included. For instance, see https://bugzilla.redhat.com/show_bug.cgi?id=2318617
=> Enable currently available translations

src/lib/portable_endian.h
[bl]eXtoh series macros have been defined in various BSD flavors.
Fixes: 30fc562 ("Include portable_endian.h")
https://github.com/NetBSD/src/blob/4899054afd533952882729ef59a0fae9a3bb397d/sys/sys/endian.h#L176
https://github.com/freebsd/freebsd-src/blob/818c7b769a4f7d3c8fecc4cf491f4e22ef816eba/sys/sys/_endian.h#L113 
https://github.com/DragonFlyBSD/DragonFlyBSD/blob/167a410d9720e60c8a92f4c69bb9a87d37572402/sys/sys/endian.h#L69
=> Fix build for various BSD flavors
